version: '3'
services:
  nodejs-1:
    build: ./nodeapp/node-1
    hostname: node_1
    ports: 
      - '5001:5001'
  nodejs-2:
    build: ./nodeapp/node-2
    hostname: node_2
    ports: 
      - '5002:5002'
  nginx: 
    build: ./nginx
    ports:
      - '80:80'

    depends_on:
      - nodejs-1
      - nodejs-2